CREATE TABLE MEMBER (
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, # ID
regDate DATETIME NOT NULL, # CREATE DATE
updateDate DATETIME NOT NULL, # UPDATE DATE
loginId CHAR(50) NOT NULL UNIQUE, # LOGIN ID
loginPW CHAR(200) NOT NULL, # LOGIN PASSWORD
name CHAR(100) NOT NULL, # NAME
nickname CHAR(100) NOT NULL, # NICK NAME
email CHAR(100) NOT NULL, # EMAIL
phone CHAR(20) NOT NULL # PHONE NUMBER
);

CREATE TABLE BOARD1 (
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, # ID
regDate DATETIME NOT NULL, # CREATE DATE
updateDate DATETIME NOT NULL, # UPDATE DATE
name CHAR(100) NOT NULL, # BOARD NAME
code CHAR(20) NOT NULL # BOARD CODE
);

CREATE TABLE ARTICLE (
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, # ID
regDate DATETIME NOT NULL, # CREATE DATE
updateDate DATETIME NOT NULL, # UPDATE DATE
boardId INT(10) UNSIGNED NOT NULL, # BOARD ID
memberId INT(10) UNSIGNED NOT NULL, # WRITER ID
content TEXT NOT NULL, # CONTENT
replyContent TEXT NOT NULL, # REPLY CONTENT
displayStatus TINYINT(1) UNSIGNED NOT NULL, # DISPLAY STATUS
delStatus TINYINT(1) UNSIGNED NOT NULL, # DELETE STATUS
delDate DATETIME UNSIGNED NOT NULL, # DELETE DATE
typeCode CHAR(20) NOT NULL, # FIRST CATEGORY
type2Code CHAR(20) NOT NULL, # SECOND CATEGORY
readStatus TINYINT(1) UNSIGNED NOT NULL, # RECEIVE STATUS
readDate DATETIME NOT NULL, # RECEIVE DATE
completeStatus TINYINT(1) UNSIGNED NOT NULL, # COMPLETE STATUS
completeDate DATETIME NOT NULL, # COMPLETE DATE
writerName CHAR(20) NOT NULL, # WRITE NAME
writerEmail CHAR(100) NOT NULL, # WRITER EMAIL
writerPhone CHAR(20) NOT NULL, # WRITER PHONE
writerSnsType CHAR(20) # WRITER SNS TYPE
writerSnsId CHAR(20) # WRITER SNS ID
);